### ISSUE TITLE
Moves model Muc does not find js script

### ISSUE THREAD

**Issue by cllorca1** [msmobility/silo#46]
After mergin master with carlos_mito2matsim the MovesModelMuc did not found the javascript for SelectRegionCalc and SelectDwellingCalc. 

Apparently solved by changing 
this.getClass().getResourceAsStream("SelectDwellingCalc")
to:
this.getClass().**_getSuperclass()_**.getResourceAsStream("SelectDwellingCalc")

(This change has been done only in carlos_mito2matsim branch via e76a46c , any better solution?)

**Comment by nkuehnel** [comment]
Ah makes sense, thanks for the hint. I moved MovesModelMstm and MovesModelMuc to "mstm" and "munich" subpackage, while there's also now an abstract superclass in the relocation package which is why getSuperClass also works. I think the javascripts should just be moved to a similar subpackage in the resource folder
