### ISSUE TITLE
Should base year be a property?

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/silo#54]
The base year is currently set in each main method:  
     SiloUtil.setBaseYear(2000);

COuld it also be a property in the properties file?

**Comment by moeckel** [comment]
I believe that we set the base year in the code, because changing it would make some steps invalid. For example, job growth is interpolated with a reference to the base year. You can start the model in a different year if you previously wrote out the synthetic population for that year (for example, if you test policies for 2030, you can start those model runs in 2030). But I believe there are some steps that refer to the base year (2000 in MD). Changing the base year requires to change some further input data, I believe. That's why I didn't want to allow the user to change it.

**Comment by nkuehnel** [comment]
So it could be a fixed attribute of the Implementation?

**Comment by moeckel** [comment]
Yes, that's exactly right.
