### ISSUE TITLE
Why does the class HouseholdDataManager.findMarriedCouple() sort households?

### ISSUE THREAD

**Issue by moeckel** [msmobility/silo#74]

**Comment by nkuehnel** [comment]
It seems it is to save some computation time. the function is looking for only one couple, which is often the married parents. so the method starts iterating from the oldest person and tries to find the most likely partner. if a partner is found the method returns so it does not need to go through the other persons. Otherwise the next oldest person is checked

**Comment by moeckel** [comment]
Sounds good, that makes sense.
